"""Generate HTML backtest reports with embedded charts and metrics."""

import base64
import os
from datetime import datetime
from typing import Optional


class ReportGenerator:
    """Generate self-contained HTML backtest reports."""

    def generate_report(
        self,
        metrics: dict,
        output_path: str,
        title: str = "Kronos Backtest Report",
        data_path: str = "",
        model_path: str = "",
        chart_path: Optional[str] = None,
    ) -> str:
        """
        Generate an HTML report with metrics and embedded chart.

        Args:
            metrics: Metrics dict from CryptoBacktester.calculate_metrics()
            output_path: Path to save the HTML report
            title: Report title
            data_path: Path to the data file used
            model_path: Path to the model used
            chart_path: Path to the chart PNG. If None, looks for backtest_chart.png in same dir.

        Returns:
            Path to the saved report
        """
        # Find chart
        if chart_path is None:
            chart_path = os.path.join(os.path.dirname(output_path), "backtest_chart.png")

        chart_b64 = ""
        if os.path.exists(chart_path):
            with open(chart_path, "rb") as f:
                chart_b64 = base64.b64encode(f.read()).decode("utf-8")

        # Format metrics
        metrics_rows = ""
        for key, value in metrics.items():
            if isinstance(value, float):
                if any(x in key for x in ["return", "rate", "drawdown"]):
                    formatted = f"{value:.2%}"
                else:
                    formatted = f"{value:.4f}"
            else:
                formatted = str(value)
            label = key.replace("_", " ").title()
            metrics_rows += f"<tr><td>{label}</td><td><strong>{formatted}</strong></td></tr>"

        generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            max-width: 1000px;
            margin: 0 auto;
            padding: 20px;
            background: #f5f5f5;
        }}
        h1 {{
            color: #1a1a2e;
            border-bottom: 3px solid #1f77b4;
            padding-bottom: 10px;
        }}
        .meta {{
            color: #666;
            font-size: 14px;
            margin-bottom: 20px;
        }}
        .metrics-table {{
            width: 100%;
            border-collapse: collapse;
            background: white;
            border-radius: 8px;
            overflow: hidden;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            margin-bottom: 20px;
        }}
        .metrics-table td {{
            padding: 10px 16px;
            border-bottom: 1px solid #eee;
        }}
        .metrics-table td:first-child {{
            color: #555;
            width: 50%;
        }}
        .metrics-table tr:last-child td {{
            border-bottom: none;
        }}
        .chart {{
            background: white;
            border-radius: 8px;
            padding: 20px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            text-align: center;
        }}
        .chart img {{
            max-width: 100%;
            height: auto;
        }}
        .footer {{
            margin-top: 20px;
            color: #999;
            font-size: 12px;
            text-align: center;
        }}
    </style>
</head>
<body>
    <h1>{title}</h1>
    <div class="meta">
        <p>Generated: {generated_at}</p>
        <p>Data: <code>{data_path}</code></p>
        <p>Model: <code>{model_path}</code></p>
    </div>

    <h2>Performance Metrics</h2>
    <table class="metrics-table">
        {metrics_rows}
    </table>

    {"<h2>Equity Curve & Drawdown</h2><div class='chart'><img src='data:image/png;base64," + chart_b64 + "' alt='Backtest Chart'></div>" if chart_b64 else ""}

    <div class="footer">
        <p>Generated by Kronos Family Office Backtest System</p>
    </div>
</body>
</html>"""

        os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(html)

        print(f"HTML report saved to {output_path}")
        return output_path
